keys:
  - &users:
    - &cole AEFF4E9E3CD49283A3AEABB88ECA55FD05C67FF0
  - &hosts:
    - &astroid age1mazs0hzm2v2lvw5l24le9vfxfqsqy260j8v28n6l44pmhhqr2sqslcnm8m
    - &pulsar age1y24tyr3fyfpflk03s0f7drctfqn9ez99kc3mfx38evj692d5cucq40uwt2

# Requires both gpg user and age host key
creation_rules:
  - path_regex: systems/x86_64-linux/pulsar/secrets.ya?ml$
    key_groups:
      - pgp:
        - *cole
        age:
        - *pulsar
  - path_regex: systems/secrets.ya?ml$
    key_groups:
      - pgp:
        - *cole
        age:
        - *astroid
        - *pulsar

